INPUT_NAME = "question"
RESPONSE_COL_NAME = "category"
TRAINING_DATA_FILEPATH = ""
TESTING_DATA_FILEPATH = ""
DUMMY_DATA_FILEPATH = "../data/example-training-data.csv"
DUMMY_DATA_NEW_FILEPATH = "../data/example-new-data.csv"